### ISSUE TITLE
error on geolayout import

### ISSUE THREAD

**Issue by QuantumV2** [Fast-64/fast64#341]
```
Traceback (most recent call last):
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 1550, in execute
    armatureMeshGroups, armatureObj = parseGeoLayout(
                                      ^^^^^^^^^^^^^^^
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 103, in parseGeoLayout
    currentAddress, armatureMeshGroups = parseNode(
                                         ^^^^^^^^^^
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 277, in parseNode
    currentAddress, newArmatureMeshGroups = parseNode(
                                            ^^^^^^^^^^
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 277, in parseNode
    currentAddress, newArmatureMeshGroups = parseNode(
                                            ^^^^^^^^^^
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 376, in parseNode
    currentAddress, nextParentBoneName, nextParentTransform = parseDLWithOffset(
                                                              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_parser.py", line 927, in parseDLWithOffset
    parseF3DBinary(
  File "C:\Users\quantumv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\fast64\fast64_internal\f3d\f3d_parser.py", line 102, in parseF3DBinary
    f3d = F3D("F3D", False)
          ^^^^^^^^^^^^^^^^^
TypeError: F3D.__init__() takes 2 positional arguments but 3 were given
```
![image](https://github.com/Fast-64/fast64/assets/83087109/1a56ef6d-48b9-4e54-a8a6-36f477fb91ff)
![image](https://github.com/Fast-64/fast64/assets/83087109/0bf96567-00ad-4260-a457-0e5da429c72e)

i was attempting to follow the following video: https://www.youtube.com/watch?v=2esvnWE3QsE

**Comment by Lilaa3** [comment]
Hello! This has been fixed, please update your fast64 here:
![image](https://github.com/Fast-64/fast64/assets/87947656/54da06f5-9b80-43f3-8036-fff336abe1ff)

**Comment by QuantumV2** [comment]
the error still persists even after updating to 2.2.0
![image](https://github.com/Fast-64/fast64/assets/83087109/08762793-0dec-44b2-813c-000da221c7ca)

**Comment by QuantumV2** [comment]
the issue persists after updating
![image](https://github.com/Fast-64/fast64/assets/83087109/8480b80d-a383-401f-b3ff-c65fd53d0dad)

**Comment by QuantumV2** [comment]
thank you that fixed it!
